"""empty message

Revision ID: 2191daf8e8b3
Revises: 9cb40a93925e
Create Date: 2023-07-23 02:24:24.751251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2191daf8e8b3'
down_revision = '9cb40a93925e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
