"""empty message

Revision ID: 9c9c42eea865
Revises: d5c94571cfc9
Create Date: 2023-07-23 03:19:18.489165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c9c42eea865'
down_revision = 'd5c94571cfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('product_size_unique', ['product_id', 'size_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.drop_constraint('product_size_unique', type_='unique')
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
