"""empty message

Revision ID: d5c94571cfc9
Revises: 2191daf8e8b3
Create Date: 2023-07-23 02:43:44.608094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c94571cfc9'
down_revision = '2191daf8e8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('size_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('product_sizes_quantity_unique', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sizes_quantity', schema=None) as batch_op:
        batch_op.create_unique_constraint('product_sizes_quantity_unique', ['product_id', 'size_id'])
        batch_op.alter_column('size_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
